### ISSUE TITLE
Background vidéo instruction

### ISSUE THREAD

**Issue by ell3s** [ell3s/ell3s.github.io#6]
> Partie 1 
"Pour répondre secouer le téléphone"

> Transition 1 
"Je marchais tranquillement dans la rue quand soudain..." 

> Partie 2 
"je continue le chemain l'air de rien ou je me retourne voir qui c'est" 

> Transition 2 
"j'arrive enfin chez mon ami..."

> Partie 3 
"Une personne de la soirée arrive vers moi"

> Transition 3 
"Par politesse j'accepte de danser"

> Partie 4 
"Il me dit quelque chose mais le volume sonore de la fête augmente..."

> Transition 4
"On entre dans la chambre. Il ferme la porte derrière nous"

> Transition 5 
"Mais il continu, il est allé trop loin"

> Transition 6 
(Déclanchement de l'explosion 1 )

> Transition 7 
(Déclanchement de l'explosion 2 )

> Partie 8
62 000 Femmes sont victimes chaque années...

>Transition 8
(Juste après lancer le dernier background)

**Comment by b2renger** [comment]
Merci je regarde ça demain !
